### ISSUE TITLE
CSS Injection 취약점

### ISSUE THREAD

**Issue by leehj050211** [J1min/Text-app#1]
### Describe

[예시 링크](https://text-297esio0i-iamjimni.vercel.app/generate?fontSize=186&content=WOW&color=dd1919;background-image:url(%27https://bssm.kro.kr/favicon.ico%27);transform:%20matrix(1,%20-0.3,%200,%201,%200,%200)rotateX(180deg))

[index.tsx](https://github.com/J1min/Text-app/blob/b1a81f49debbda86d5cac7898364dda3d9553767/pages/generate/index.tsx) 여기 코드를 보면 사용자의 입력을 어떠한 필터링 없이 바로 css를 주입하는 것을 볼 수 있습니다.
이 취약점을 이용하면 심한경우 사용자의 input 값도 탈취할 수 있으니 조심해주시기 바랍니다.

**Comment by J1min** [comment]
탈취 돼도 괜찮지 않을까요? 
꿀팁 감사드립니다 😊

**Comment by J1min** [comment]
<img width="592" alt="스크린샷 2023-01-08 오후 2 00 07" src="https://user-images.githubusercontent.com/80014454/211181305-d386999f-f13d-4667-b2b2-f7470c05f71e.png">

이런식으로 고치려고 시도해보았지만 빌드 과정에서 substring을 받아들이지 못해서 실패했습니다 다음엔 더 분발하도록 하겠습니다.
